language: node_js
node_js:
  - 9
script:
  - yarn build

cache:
  yarn: true
deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: docs
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      tags: true
